### ISSUE TITLE
consul_keys resource not detecting missing keys from consul

### ISSUE THREAD

**Issue by PurrBiscuit** [terraform-providers/terraform-provider-consul#76] opened 2018-12-10 19:42 UTC
Hello,

We have an issue where consul keys had been set via terraform (using the config pasted below) and making it to state file just fine but when they had been deleted in the console, terraform wasn't detecting that those keys were missing and needed to get recreated on subsequent plans.  It's almost as if it's running with `-refresh=false` and the `consul_keys` resource isn't reaching out to consul to perform a refresh at all.

To be clear, we are not passing in the `-refresh=false` flag here when running `terraform plan`.  It just seems like it is being passed with this resource.

### Terraform Version
0.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- consul_keys

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "consul_keys" "dns" {
  key {
    path   = "global/env_vars/EXAMPLE_API_URI"
    value  = "http://example.com"
    delete = true
  }

  key {
    path   = "global/env_vars/EXAMPLE_API_PRIV_URI"
    value  = "http://example.priv"
    delete = true
  }
}
```

### Expected Behavior
Missing consul keys that had been previously set by terraform, and are in state file, should be detected and recreated on subsequent terraform plan/apply.

### Actual Behavior
Missing consul keys aren't being detected and a zero diff is output for a terraform plan.

### Steps to Reproduce
1. `terraform apply` the config above and get consul keys created via terraform.
2. delete those keys from console manually (outside of terraform's control)
3. run `terraform plan` and see no detected changes (where it should be trying to add those keys again.

**Comment by remilapeyre** [comment] 2018-12-12 12:54
Hi @PurrBiscuit, thanks for the bug report!

If I understand correctly, Terraform does not refresh its state correctly in some situation.

I have not been able to reproduce your bug, here's what I tried:
```bash
➜  temp cat example.tf
resource "consul_keys" "dns" {
  key {
    path   = "global/env_vars/EXAMPLE_API_URI"
    value  = "http://example.com"
    delete = true
  }

  key {
    path   = "global/env_vars/EXAMPLE_API_PRIV_URI"
    value  = "http://example.priv"
    delete = true
  }
}
➜  temp terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "consul" (2.2.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.consul: version = "~> 2.2"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
➜  temp terraform version
Terraform v0.11.2
+ provider.consul v2.2.0

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html
➜  temp terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + consul_keys.dns
      id:                     <computed>
      datacenter:             <computed>
      key.#:                  "2"
      key.1593199023.default: ""
      key.1593199023.delete:  "true"
      key.1593199023.name:    ""
      key.1593199023.path:    "global/env_vars/EXAMPLE_API_PRIV_URI"
      key.1593199023.value:   "http://example.priv"
      key.2973406437.default: ""
      key.2973406437.delete:  "true"
      key.2973406437.name:    ""
      key.2973406437.path:    "global/env_vars/EXAMPLE_API_URI"
      key.2973406437.value:   "http://example.com"
      var.%:                  <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

consul_keys.dns: Creating...
  datacenter:             "" => "<computed>"
  key.#:                  "" => "2"
  key.1593199023.default: "" => ""
  key.1593199023.delete:  "" => "true"
  key.1593199023.name:    "" => ""
  key.1593199023.path:    "" => "global/env_vars/EXAMPLE_API_PRIV_URI"
  key.1593199023.value:   "" => "http://example.priv"
  key.2973406437.default: "" => ""
  key.2973406437.delete:  "" => "true"
  key.2973406437.name:    "" => ""
  key.2973406437.path:    "" => "global/env_vars/EXAMPLE_API_URI"
  key.2973406437.value:   "" => "http://example.com"
  var.%:                  "" => "<computed>"
consul_keys.dns: Creation complete after 0s (ID: consul)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
➜  temp consul kv delete global/env_vars/EXAMPLE_API_PRIV_URI
Success! Deleted key: global/env_vars/EXAMPLE_API_PRIV_URI
➜  temp terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

consul_keys.dns: Refreshing state... (ID: consul)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ consul_keys.dns
      key.1593199023.default: "" => ""
      key.1593199023.delete:  "" => "true"
      key.1593199023.name:    "" => ""
      key.1593199023.path:    "" => "global/env_vars/EXAMPLE_API_PRIV_URI"
      key.1593199023.value:   "" => "http://example.priv"
      key.2973406437.default: "" => ""
      key.2973406437.delete:  "true" => "true"
      key.2973406437.name:    "" => ""
      key.2973406437.path:    "global/env_vars/EXAMPLE_API_URI" => "global/env_vars/EXAMPLE_API_URI"
      key.2973406437.value:   "http://example.com" => "http://example.com"
      key.511490872.default:  "" => ""
      key.511490872.delete:   "true" => "false"
      key.511490872.name:     "" => ""
      key.511490872.path:     "global/env_vars/EXAMPLE_API_PRIV_URI" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Maybe we do not have the same version of the Consul Terraform provider, can you paste the output of `terraform version`?

**Comment by remilapeyre** [comment] 2018-12-12 14:19
This is weird, does it always happen or was it only once?

**Comment by PurrBiscuit** [comment] 2018-12-12 14:57
I've seen it happen once for us but can try to reproduce again.  I had to remove the `consul_keys` resource from the terraform state with `terraform state rm consul_keys.dns` to get it to recreate those keys after they had been deleted from our consul cluster.

**Comment by remilapeyre** [comment] 2018-12-13 18:47
I'm not sure what the underlying cause may be, the issue may have been with Consul consistency if it never happens again.

If you can give the Consul version, and the configuration of your Consul cluster, I can try to replicate it to see if this change something (I think agents don't cache KV and that only masters answer but it's worth a try).

**Comment by remilapeyre** [comment] 2020-06-06 15:44
Hi @PurrBiscuit, since it looks like this issue never happened again I will close it. Please reopen it if needed.

**Closed by remilapeyre** 2020-06-06 15:44 UTC
