### ISSUE TITLE
data.consul_key_prefix usage doesn't match documentation

### ISSUE THREAD

**Issue by tiagowegner** [terraform-providers/terraform-provider-consul#66] opened 2018-09-28 18:59 UTC
I'm trying to use data.consul_key_prefix to batch read keys from consul, but terraform fails with "data variables must be four parts: data.TYPE.NAME.ATTR" even though I'm following [this](https://www.terraform.io/docs/providers/consul/d/key_prefix.html) document.
### Terraform Version
Terraform v0.11.8
+ provider.consul v2.1.0

### Affected Resource(s)
- consul_key_prefix

### Terraform Configuration Files
```hcl
provider "consul" {
  address = "consul.local:443"
  scheme  = "https"
}

data "consul_key_prefix" "aws-environment" {
  token = "yeah-right"
  datacenter = "local"

  path_prefix = "terraform/config/aws-env/${terraform.workspace}/"
}

# Module Outputs
output "vpc_id" {
  value = "${data.consul_key_prefix.aws-environment["vpc_id"]}"
}

```

### Debug Output
2018/09/28 15:56:39 [INFO] Terraform version: 0.11.8  7a5c1d221ac209bbac66947c369815cd9ca70ed5
2018/09/28 15:56:39 [INFO] Go runtime version: go1.10.1
2018/09/28 15:56:39 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}
2018/09/28 15:56:39 [DEBUG] Attempting to open CLI config file: /home/tiago_wegner/.terraformrc
2018/09/28 15:56:39 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/09/28 15:56:39 [INFO] CLI command args: []string{"plan"}
2018/09/28 15:56:39 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error loading /home/tiago_wegner/repo/tf-modules/aws-environment/main.tf: Error reading config for output account_id: data.consul_key_prefix.aws-environment: data variables must be four parts: data.TYPE.NAME.ATTR in:

${data.consul_key_prefix.aws-environment["vpc_id"]}

### Expected Behavior
Keys should be correctly read from consul kv store.

### Actual Behavior
Error: Error loading /home/tiago_wegner/repo/tf-modules/aws-environment/main.tf: Error reading config for output account_id: data.consul_key_prefix.aws-environment: data variables must be four parts: data.TYPE.NAME.ATTR in:

${data.consul_key_prefix.aws-environment["vpc_id"]}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Nothing in particular

### References
None

**Comment by tiagowegner** [comment] 2018-09-28 20:21
Looking into the source I've noticed that appending a ".subkeys" makes everything work.
${data.consul_key_prefix.aws-environment["vpc_id"]} -> ${data.consul_key_prefix.aws-environment.subkeys["vpc_id"]}

**Comment by barsenault-strike** [comment] 2018-10-01 19:59
Using `.subkeys` as well has been problematic for me because it seems to include an element representing the target key in addition to the rest of the subkeys.

```
Outputs:

lambda_env_vars = {
  / =
  /testkey1 = one
  /testkey2 = two
  /testkey3 = three
}
```

It'll work for your situation where you're trying to match against a map but strictly speaking the `subkeys` attribute isn't returning _only subkeys_.

**Comment by natefaerber** [comment] 2018-10-01 20:36
Sorry.  I'm just seeing this now.  I must have skipped it in my inbox.  Looks like I did leave out the `.subkeys` ATTR from the example.  I can update that.  I'll see about updating the test case and code so it doesn't return the parent key.

**Comment by barsenault-strike** [comment] 2018-10-01 20:51
Awesome! In the meantime I was able to get around the empty element with this ugliness:

```
  environment {
    variables = "${zipmap(compact(keys(data.consul_key_prefix.lambda.subkeys)),compact(values(data.consul_key_prefix.lambda.subkeys)))}"
  }
```

But I'd love to just use `.subkeys` as theorized!

**Comment by natefaerber** [comment] 2018-10-01 21:29
Hmmm.  I can't seem to reproduce this:

```
lambda_env_vars = {
  / =
  /testkey1 = one
  /testkey2 = two
  /testkey3 = three
}
```

I suspect that your KV store was created in a strange way.  I don't understand why there is a `/` in front of all your keys.  I can reproduce this scenario this way:

```
consul kv put lambda/
consul kv put lambda/testkey1 one
consul kv put lambda/testkey2 two
consul kv put lambda/testkey3 three
```

I suggest running `consul kv export <prefix>` to verify this.  You will see something like this where lambda is my prefix:

```
[
	{
		"key": "lambda/",
		"flags": 0,
		"value": ""
	},
...
]
```

Run `consul kv delete <prefix>` where prefix ends with the `/` and you should probably see the empty value disappear.

There is nothing I can really do about this because `<prefix>` was given an empty value so the provider is doing what it was supposed to do.  Make sense?

**Comment by barsenault-strike** [comment] 2018-10-02 17:00
You know I thought that was going to confuse and so I went back and edited in the output from the way I'm doing it, which doesn't produce a `/`. 

  ```
  data "consul_key_prefix" "lambda" {
    provider = "consul.${var.environment}"
    path_prefix = "our-lambda-path/${var.lambda_name}/"  <--- just a matter of this string
  }
  ```

Without the `/` on the end of the `path_prefix` string you get it in the keys (`/`, `/testkey1`, etc). But _either way_ you get an extra element in the map for the parent key:

```lambda_env_vars = {
  / =
  /testkey1 = one
  /testkey2 = two
  /testkey3 = three
}
```
```
lambda_env_vars = {
   =
  testkey1 = one
  testkey2 = two
  testkey3 = three
}
```

Hope that clarifies! That said, you are totally correct about there being a parent key entry:
```
ubuntu@consul-3:~$ consul kv export consul-config/terraformed_lambda_template/
[
	{
		"key": "consul--path/terraformed_lambda_template/",
		"flags": 0,
		"value": ""
	},
	{
		"key": "consul-path/terraformed_lambda_template/testkey1",
		"flags": 0,
		"value": "b25l"
	},
	{
		"key": "consul-path/terraformed_lambda_template/testkey2",
		"flags": 0,
		"value": "dHdv"
	},
	{
		"key": "consul-path/terraformed_lambda_template/testkey3",
		"flags": 0,
		"value": "dGhyZWU="
	}
]
```

How does this happen? I used the Consul UI to edit those keys in by hand while I was developing, adding the `terraformed_lambda_template/` folder and then the test subkeys. Is that intended? Would this have been avoided if the subkeys were instead provisioned without a folder first?

**Comment by pearkes** [comment] 2018-10-02 23:33
I noted when I merged the above PR that this may not resolve your issue @barsenault-strike. Let me know if that is the case and we can re-open this.

**Closed** 2018-10-02 23:32 UTC
